# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0060_auto_20150907_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buurt',
            name='stadsdeel',
        ),
        migrations.RemoveField(
            model_name='ligplaats',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='ligplaats',
            name='buurt',
        ),
        migrations.RemoveField(
            model_name='ligplaats',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='ligplaats',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='openbare_ruimte',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='standplaats',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nummeraanduiding',
            name='verblijfsobject',
        ),
        migrations.RemoveField(
            model_name='openbareruimte',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='openbareruimte',
            name='status',
        ),
        migrations.RemoveField(
            model_name='openbareruimte',
            name='woonplaats',
        ),
        migrations.RemoveField(
            model_name='pand',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stadsdeel',
            name='gemeente',
        ),
        migrations.RemoveField(
            model_name='standplaats',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='standplaats',
            name='buurt',
        ),
        migrations.RemoveField(
            model_name='standplaats',
            name='status',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='buurt',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='eigendomsverhouding',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='financieringswijze',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='gebruik',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='ligging',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='locatie_ingang',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='panden',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='reden_afvoer',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='verblijfsobject',
            name='toegang',
        ),
        migrations.RemoveField(
            model_name='verblijfsobjectpandrelatie',
            name='pand',
        ),
        migrations.RemoveField(
            model_name='verblijfsobjectpandrelatie',
            name='verblijfsobject',
        ),
        migrations.RemoveField(
            model_name='woonplaats',
            name='gemeente',
        ),
        migrations.DeleteModel(
            name='Bron',
        ),
        migrations.DeleteModel(
            name='Buurt',
        ),
        migrations.DeleteModel(
            name='Eigendomsverhouding',
        ),
        migrations.DeleteModel(
            name='Financieringswijze',
        ),
        migrations.DeleteModel(
            name='Gebruik',
        ),
        migrations.DeleteModel(
            name='Gemeente',
        ),
        migrations.DeleteModel(
            name='Ligging',
        ),
        migrations.DeleteModel(
            name='Ligplaats',
        ),
        migrations.DeleteModel(
            name='LocatieIngang',
        ),
        migrations.DeleteModel(
            name='Nummeraanduiding',
        ),
        migrations.DeleteModel(
            name='OpenbareRuimte',
        ),
        migrations.DeleteModel(
            name='Pand',
        ),
        migrations.DeleteModel(
            name='RedenAfvoer',
        ),
        migrations.DeleteModel(
            name='Stadsdeel',
        ),
        migrations.DeleteModel(
            name='Standplaats',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Toegang',
        ),
        migrations.DeleteModel(
            name='Verblijfsobject',
        ),
        migrations.DeleteModel(
            name='VerblijfsobjectPandRelatie',
        ),
        migrations.DeleteModel(
            name='Woonplaats',
        ),
    ]
